### PR TITLE
Enhance/Correct test-case for pattern definitions

### PR DESCRIPTION
**Pull request by DimStar77**
The out/patterns is about what I'd expect it to be once corrected.

### CODE REVIEW

**Comment by scarabeusiv** [comment]
@simotek could you pretty please check if the resulting output is pleasing to your eyes? :)

**Comment by simotek** [comment]
I think the Requires: / Recommends: for other patterns should come after the Provides and Obsoletes, the first case in the diff is right, but the second and third aren't

**Comment by DimStar77** [comment]
Arguably - but I can live with it :) - will adjust the test case

**Comment by DimStar77** [comment]
Updated the test case... I intentinally 'messed' the input file up a bit more - so the sorting algo can be better tested :)

**Comment by scarabeusiv** [comment]
Oky so let me merge this ;)

**Pull request merged**
