### PR TITLE
 Create two new groups for Haskell packages

### PR DESCRIPTION
**Pull request by peti**
Suggested by @jengelh.

### CODE REVIEW

**Comment by jengelh** [comment]
We should stick to one group - or what's the use for two? And how is the user going to tell the difference?

**Comment by peti** [comment]
Well, `Devel/Languages/Haskell` is used to tools and executables that Haskell packages install. `Devel/Libraries/Haskell`, on the other hand, is used for re-usable libraries found in `-devel` packages.

What else would you suggest?

**Comment by peti** [comment]
FYI: all spec files in https://build.opensuse.org/project/show/devel:languages:haskell:lts:9 have been re-generated with the new group tags. See https://build.opensuse.org/package/rdiff/devel:languages:haskell:lts:9/ghc-aeson?linkrev=base&rev=5 for a concrete example.

**Comment by jengelh** [comment]
If I look at e.g. Perl, only one really seems to be used.
```
   1121 Group:Development/Libraries/Perl
     26 Group:Development/Languages/Perl
```
(I also don't know why some have a prevalence in /Libraries/ and others in /Languages/. It makes no sense.)

**Comment by peti** [comment]
Well, the situation in our environment is different:

~~~
$ grep -l Development/Libraries/Haskell */*spec | wc -l             
2406
$ grep -l Development/Languages/Haskell */*spec | wc -l 
2462
~~~

As I've asked before: what exactly are you suggesting? It's one thing to say that you're unhappy about these choices, but it's quite another to actually suggest an alternative.

**Comment by jengelh** [comment]
>what exactly are you suggesting?

That:

>>We should stick to one group

Which probably should mean: replace Development/Languages/Other by Development/Languages/Haskell.

**Comment by scarabeusiv** [comment]
Well the most important part is to add it to the wiki and rpm :) spec-cleaner should inherit it then.

**Comment by peti** [comment]
I'm not sure what you mean by "stick to one group". We are using *two groups* already.

> replace Development/Languages/Other by Development/Languages/Haskell

What about those 2400 occurrences of Development/Libraries/Other? Do you think we should keep those?

**Comment by jengelh** [comment]
>What about those 2400 occurrences of Development/Libraries/Other? Do you think we should keep those?

Should be replaced in the long run as well, by, for example, /C and C++. It might be reasonable though to leave "niche" languages (in the context of openSUSE) - like Fortran - in /Other.

**Pull request merged**
